apiVersion: v1
kind: Pod
metadata:
  name: primary-service
  labels:
    app: testapp
spec:
  containers:
  - name: primary-service-container
    image: psm/primary-service-docker
    ports:
    - name: rest-port
      containerPort: 8093
