apiVersion: v1
kind: Pod
metadata:
  name: secondary-service
  labels:
    app: testapp
spec:
  containers:
  - name: primary-service
    image: cilagan/secondary-service-docker:2.0.0-SNAPSHOT
    ports:
    - name: api-port
      containerPort: 8093
