apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secondary-service-v1-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: primary-service
        image: cilagan/secondary-service-docker:latest
        ports:
        - name: api-port
          containerPort: 8093
---
apiVersion: v1
kind: Service
metadata:
  name: secondary-service-service
spec:
  ports:
  - port: 8093
    nodePort: 30303
    targetPort: 8093
    protocol: TCP
    name: http
  selector:
    app: testapp
  type: NodePort
