# APPLICATION CONFIGURATION PROPERTIES #
# To implement externalized configuration
# 1. Remove this file from /src/main/resources
# 2. Configure the following OS variables
#    * SPRING_CONFIG_LOCATION
#    * SPRING_PROFILES_ACTIVE
# 3. Place this file in the SPRING_CONFIG_LOCATION directory
#     - attach an environment suffix (i.e., solicitation-dev.yml) if you require environment-specific loading
# 4. Deploy the application
# The application will load the externalized properties file during initialization
server:
    port: 8093
    
# Spring Boot settings #
security: 
    basic: 
        enabled: false              
        
endpoints:
    loggers:
        sensitive: false
        
management:
    context-path: /internal/manage
    #security:
        #enabled: false               
        
            
# Spring settings #
spring: 
    jmx: 
        enabled: false
    jndi:
        ignore: true
    jackson: 
        serialization-inclusion: non_null
        serialization:
            indent_output: true
    http: 
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
            
# Build Info #
buildinfo:
    artifact-version: 1.0.0-SNAPSHOT
    build-date: 2018-05-07 16:37:43
    java-version: 1.8.0_152 
    project-name: Primary Service
    #scm-version: @scm.version@#

